name: backend-rknn

on:
  push:
    paths:
      - "csrc/**"
      - "demo/csrc/**"
      - "CMakeLists.txt"

  pull_request:
    paths-ignore:
      - "csrc/**"
      - "demo/csrc/**"
      - "CMakeLists.txt"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_rknpu2:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: update
        run: sudo apt update
      - name: cross compile
        run: |
          sh -xe tools/scripts/ubuntu_cross_build_rknn.sh rk3588
  build_rknpu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: update
        run: sudo apt update
      - name: cross compile
        run: |
          sh -xe tools/scripts/ubuntu_cross_build_rknn.sh rv1126

  badge_build_rknpu2:
    needs: build_rknpu2
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - name: create badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: build_rknpu2
          LABEL: 'build'
          STATUS: ${{ needs.build_rknpu2.result == 'success' && 'passing' || needs.build_rknpu2.result }}
          COLOR: ${{ needs.build_rknpu2.result == 'success' && 'green' || 'red' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  badge_build_rknpu:
    needs: build_rknpu
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - name: create badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: build_rknpu
          LABEL: 'build'
          STATUS: ${{ needs.build_rknpu.result == 'success' && 'passing' || needs.build_rknpu.result }}
          COLOR: ${{ needs.build_rknpu.result == 'success' && 'green' || 'red' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
